apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: on-change-webhook
spec:
  eventBusName: mdd-event-bus
  service:
    ports:
      - port: 80
        targetPort: 80
  webhook:
    on-change:
      port: "80"
      endpoint: /onchange
      method: POST