# This event source is the target of the gitea webhook.
# It will trigger an argo event that a sensor can react to.
# Reachable under: http://on-change-webhook-eventsource-svc.mdd.svc.cluster.local/onchange
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: on-change-webhook
spec:
  eventBusName: mdd-event-bus
  service:
    ports:
      - port: 80
        targetPort: 80
  webhook:
    on-change:
      port: "80"
      endpoint: /onchange
      method: POST