argo-workflows:
  singleNamespace: false
  server:
    extraArgs: [--auth-mode=server]
    ingress:
      enabled: true
      hosts: [argo-workflows-server.argo.svc.cluster.local]
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  controller:
    workflowNamespaces: ["argo", "mdd"]