apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume
  claimRef:
    name: gitea-pvc
    namespace: default
  hostPath:
    # Maps to C:\temp\docker-volumes/gitea
    path: "/run/desktop/mnt/host/c/temp/docker-volumes/gitea"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume
  claimRef:
    name: postgresql-pvc
    namespace: default
  hostPath:
    # Maps to C:\temp\docker-volumes/postgresql
    path: "/run/desktop/mnt/host/c/temp/docker-volumes/postgresql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
